- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.shell: 
    ~/.zsh: 
    ~/.vimrc: 
    ~/.zshrc: 
    ~/.oh-my-zsh/custom/themes/:
        glob: true
        path: oh-my-zsh/custom/themes/*

- shell:
  - [git submodule update --init --recursive, Installing submodules]